project:
  name: cardvault
  language: javascript
  watched_dirs:
  - .
  - PokemonCardRecognizer
  - docs
  - memory
  - pokemon_card_vault
  - report
  - scripts
  file_extensions:
  - .cc
  - .cjs
  - .cmake
  - .conf
  - .cpp
  - .css
  - .dart
  - .entitlements
  - .example
  - .gradle
  - .h
  - .html
  - .index
  - .java
  - .js
  - .json
  - .jsonc
  - .jsonl
  - .key
  - .kt
  - .log
  - .m
  - .manifest
  - .md
  - .mdc
  - .npy
  - .pbxproj
  - .plist
  - .prisma
  - .properties
  - .pub
  - .py
  - .rc
  - .rules
  - .service
  - .sh
  - .sql
  - .storyboard
  - .swift
  - .timer
  - .toml
  - .ts
  - .txt
  - .woff2
  - .xcconfig
  - .xcscheme
  - .xcsettings
  - .xcworkspacedata
  - .xib
  - .xml
  - .yaml
  collection_name: cardvault
