name: pokecoin
description: Un'app Flutter ispirata a CardTrader per collezionare carte Pokémon.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^0.13.6
  fl_chart: ^0.66.0
  uuid: ^4.2.2  # ✅ Aggiunto per gestire gli ID univoci

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
