// Generated by scripts/generate-first-char-token-cache.js. Do not edit by hand.

class FirstCharTokenSuggestion {
  const FirstCharTokenSuggestion({
    required this.display,
    required this.normalized,
    required this.confidence,
    required this.cardCount,
    required this.language,
  });

  final String display;
  final String normalized;
  final double confidence;
  final int cardCount;
  final String language;
}

const String firstCharTokenSuggestionsGeneratedAt = '2026-05-23T06:21:43.784Z';

const Map<String, FirstCharTokenSuggestion> firstCharTokenSuggestions = {
  'a': FirstCharTokenSuggestion(
      display: 'Articuno',
      normalized: 'articuno',
      confidence: 97.000000,
      cardCount: 121,
      language: 'en'),
  'b': FirstCharTokenSuggestion(
      display: 'Blastoise',
      normalized: 'blastoise',
      confidence: 96.000000,
      cardCount: 125,
      language: 'en'),
  'c': FirstCharTokenSuggestion(
      display: 'Charizard',
      normalized: 'charizard',
      confidence: 96.000000,
      cardCount: 278,
      language: 'en'),
  'd': FirstCharTokenSuggestion(
      display: 'Dragonite',
      normalized: 'dragonite',
      confidence: 96.000000,
      cardCount: 131,
      language: 'en'),
  'e': FirstCharTokenSuggestion(
      display: 'Eevee',
      normalized: 'eevee',
      confidence: 100.000000,
      cardCount: 269,
      language: 'en'),
  'f': FirstCharTokenSuggestion(
      display: 'Flareon',
      normalized: 'flareon',
      confidence: 98.000000,
      cardCount: 121,
      language: 'en'),
  'g': FirstCharTokenSuggestion(
      display: 'Gardevoir',
      normalized: 'gardevoir',
      confidence: 96.000000,
      cardCount: 147,
      language: 'en'),
  'h': FirstCharTokenSuggestion(
      display: 'Houndoom',
      normalized: 'houndoom',
      confidence: 97.000000,
      cardCount: 120,
      language: 'en'),
  'i': FirstCharTokenSuggestion(
      display: 'Inteleon',
      normalized: 'inteleon',
      confidence: 96.172736,
      cardCount: 62,
      language: 'en'),
  'j': FirstCharTokenSuggestion(
      display: 'Jolteon',
      normalized: 'jolteon',
      confidence: 98.000000,
      cardCount: 126,
      language: 'en'),
  'k': FirstCharTokenSuggestion(
      display: 'Kangaskhan',
      normalized: 'kangaskhan',
      confidence: 95.000000,
      cardCount: 102,
      language: 'en'),
  'l': FirstCharTokenSuggestion(
      display: 'Lucario',
      normalized: 'lucario',
      confidence: 98.000000,
      cardCount: 173,
      language: 'en'),
  'm': FirstCharTokenSuggestion(
      display: 'Mew',
      normalized: 'mew',
      confidence: 100.000000,
      cardCount: 155,
      language: 'en'),
  'n': FirstCharTokenSuggestion(
      display: 'N',
      normalized: 'n',
      confidence: 100.000000,
      cardCount: 45,
      language: 'en'),
  'o': FirstCharTokenSuggestion(
      display: 'Oricorio',
      normalized: 'oricorio',
      confidence: 96.586314,
      cardCount: 79,
      language: 'en'),
  'p': FirstCharTokenSuggestion(
      display: 'Pikachu',
      normalized: 'pikachu',
      confidence: 98.000000,
      cardCount: 550,
      language: 'en'),
  'q': FirstCharTokenSuggestion(
      display: 'Quaxly',
      normalized: 'quaxly',
      confidence: 97.297513,
      cardCount: 37,
      language: 'en'),
  'r': FirstCharTokenSuggestion(
      display: 'Raichu',
      normalized: 'raichu',
      confidence: 99.000000,
      cardCount: 186,
      language: 'en'),
  's': FirstCharTokenSuggestion(
      display: 'Snorlax',
      normalized: 'snorlax',
      confidence: 98.000000,
      cardCount: 156,
      language: 'en'),
  't': FirstCharTokenSuggestion(
      display: 'Tyranitar',
      normalized: 'tyranitar',
      confidence: 96.000000,
      cardCount: 117,
      language: 'en'),
  'u': FirstCharTokenSuggestion(
      display: 'Ultra Ball',
      normalized: 'ultraball',
      confidence: 96.000000,
      cardCount: 175,
      language: 'en'),
  'v': FirstCharTokenSuggestion(
      display: 'Vulpix',
      normalized: 'vulpix',
      confidence: 99.000000,
      cardCount: 143,
      language: 'en'),
  'w': FirstCharTokenSuggestion(
      display: 'Wooper',
      normalized: 'wooper',
      confidence: 98.520144,
      cardCount: 76,
      language: 'en'),
  'x': FirstCharTokenSuggestion(
      display: 'Xerneas',
      normalized: 'xerneas',
      confidence: 97.403910,
      cardCount: 71,
      language: 'en'),
  'y': FirstCharTokenSuggestion(
      display: 'Yveltal',
      normalized: 'yveltal',
      confidence: 97.770880,
      cardCount: 88,
      language: 'en'),
  'z': FirstCharTokenSuggestion(
      display: 'Zoroark',
      normalized: 'zoroark',
      confidence: 98.000000,
      cardCount: 131,
      language: 'en'),
};
