insert into public.marketplace_cm_expansion_parsing (
  expansion_name,
  cardtrader_expansion_code,
  cardmarket_locale,
  cardmarket_expansion_slug,
  cardmarket_set_code,
  cardmarket_context_code,
  number_format_rule,
  applies_to_card_type,
  confidence,
  notes,
  verified_at
)
values
  (
    'Astral Radiance',
    'swsh10',
    'en',
    'Astral-Radiance',
    'ASR',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'Refinement log verified Sweet Honey URL uses Astral-Radiance slug and ASR153 product code.',
    now()
  ),
  (
    'Advent of Arceus',
    'pt4',
    'en',
    'Advent-of-Arceus',
    'Pt4',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'Refinement log verified Rescue maps to Pokemon-Rescue-Pt4080; Cardmarket can rename Trainer rows and uses mixed-case Pt4 product code.',
    now()
  ),
  (
    'Dragon Majesty',
    'drm',
    'en',
    'Dragon-Majesty',
    'DRM',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'Refinement log verified Dragon Majesty uses DRM product codes such as Hydreigon-DRM33.',
    now()
  ),
  (
    'EX Holon Phantoms',
    'exhp',
    'en',
    'EX-Holon-Phantoms',
    'HP',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Mew ex HP100 URL maps EX Holon Phantoms to EX-Holon-Phantoms and HP product codes.',
    now()
  ),
  (
    'Start Deck 100',
    'sl',
    'en',
    'Start-Deck-100',
    'sI100',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Aroma Lady URL uses Cardmarket set code sI100, not CardTrader sl/SL.',
    now()
  ),
  (
    'Unbroken Bonds',
    'unb',
    'it',
    'Unbroken-Bonds',
    'UNB',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Togekiss URL uses code-suffixed product slug.',
    now()
  ),
  (
    'Night Unison',
    'sm9a',
    'it',
    'Night-Unison',
    '',
    '',
    'name_only',
    'trainer',
    'verified',
    'User verified Trainer card Surprise Box URL uses name-only product slug.',
    now()
  ),
  (
    'Rising Fist',
    'xy2',
    'en',
    'Rising-Fist',
    '',
    '',
    'name_only',
    'trainer',
    'verified',
    'User verified Trainer/Stadium card Training Center URL uses name-only product slug.',
    now()
  ),
  (
    'MEGA Dream ex',
    'm2a',
    'en',
    'MEGA-Dream-ex',
    'm2a',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Hops Zacian ex URL uses lower-case m2a product code and no apostrophe separator.',
    now()
  ),
  (
    'CSM1c: Storming Emergence - Abundant',
    'csm1c',
    'es',
    'Storming-Emergence-Abundant',
    'CSM1cC',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Pokemon Fan Club URL drops CSM prefix from expansion slug and includes V1 marker.',
    now()
  ),
  (
    'CSM1c: Storming Emergence - Abundant',
    'csm1c',
    'en',
    'Storming-Emergence-Abundant',
    'CSM1cC',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Cynthia URL uses English locale, Storming-Emergence-Abundant expansion slug, Cardmarket set code CSM1cC, and V2 marker.',
    now()
  ),
  (
    'Skyridge',
    'skg',
    'en',
    'Skyridge',
    'SK',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'Cardmarket Skyridge URLs use SK, not CardTrader skg/SKG; verified from Lapras and Steelix examples.',
    now()
  ),
  (
    'Phantasmal Flames',
    'pfl',
    'it',
    'Phantasmal-Flames',
    'PFL',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Ambipom Illustration Rare URL uses Italian locale and V2 marker because Ambipom has multiple printings in this expansion.',
    now()
  ),
  (
    'Phantom Forces',
    'phf',
    'en',
    'Phantom-Forces',
    'PHF',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Dedenne URL uses English locale and code-suffixed product slug.',
    now()
  ),
  (
    'XY Trainer Kit: Pikachu Libre & Suicune (Suicune)',
    'suicune',
    'en',
    'XY-Trainer-Kit-Pikachu-Libre-Suicune',
    'TK9S',
    '',
    'context_code',
    'trainer',
    'verified',
    'User verified Tierno URL uses English locale, shortened expansion slug, and TK9S context code.',
    now()
  ),
  (
    'World Championship Decks 2018',
    'wcd2018',
    'en',
    'WCD-2018',
    '',
    'WCD18CIN',
    'context_code',
    'pokemon',
    'verified',
    'User verified Buzzwole GX URL uses WCD context/player code.',
    now()
  ),
  (
    'World Championship Decks 2007',
    'wcd2007',
    'en',
    'WCD-2007',
    '',
    'WCD07CG',
    'context_code',
    'energy',
    'verified',
    'User verified WCD 2007 Double Rainbow Energy URL uses WCD07CG context code.',
    now()
  ),
  (
    'Neo Discovery',
    'neo2',
    'en',
    'Neo-Discovery',
    'NDI',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Neo Discovery Kabutops URL uses Cardmarket code NDI and no V marker.',
    now()
  ),
  (
    'S-P: Sword & Shield Promos',
    's-p',
    'en',
    'Sword-Shield-Simplified-Chinese-Promos',
    'PCS',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Friends in Alola maps to Cardmarket Simplified Chinese Promos with PCS code.',
    now()
  ),
  (
    'SWSH Black Star Promos',
    'swshbs',
    'en',
    'SWSH-Black-Star-Promos',
    'SWSH',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Rapidash URL uses SWSH promo code instead of CardTrader swshbs.',
    now()
  ),
  (
    'Clash at the Summit',
    'l3',
    'en',
    'Clash-at-the-Summit',
    'L3',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Clash at the Summit Lickitung URL uses L3 code without zero padding.',
    now()
  ),
  (
    'CS1b: Dynamax Clash - Flame',
    'cs1b',
    'en',
    'Dynamax-Clash-Flame',
    'CS1bC',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Dynamax Clash Flame Lum Berry URL uses Cardmarket expansion slug and mixed-case CS1bC code.',
    now()
  ),
  (
    'SM Black Star Promos',
    'smbs',
    'en',
    'SM-Black-Star-Promos',
    'OSSM',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Detective Pikachu URL uses OSSM code and V2 marker.',
    now()
  ),
  (
    'Rocket Gang Strikes Back',
    'rgsb',
    'en',
    'Rocket-Gang-Strikes-Back',
    'PCG3',
    '',
    'set_code_padded_3',
    'pokemon',
    'verified',
    'User verified Dark Steelix URL uses PCG3 plus three-digit collector number.',
    now()
  ),
  (
    'Cosmic Eclipse',
    'cec',
    'en',
    'Cosmic-Eclipse',
    'CEC',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Throh URL uses CEC product code; TCGdex sm12 is not the Cardmarket code.',
    now()
  ),
  (
    'CSM1d: Storming Emergence GX Starter Deck',
    'csm1d',
    'en',
    'Storming-Emergence-GX-Starter-Deck',
    'CSM1DC',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified CSM1d Starter Deck drops the CSM1d prefix from the expansion slug and uses mixed-case CSM1DC product code.',
    now()
  ),
  (
    'Darkness that Consumes Light',
    'sm3n',
    'en',
    'Darkness-that-Consumes-Light',
    '',
    '',
    'name_only',
    'pokemon',
    'verified',
    'User verified Pikachu URL uses name-only Cardmarket product slug for this expansion.',
    now()
  ),
  (
    'High Class Pack GX Ultra Shiny',
    'sm8b',
    'en',
    'GX-Ultra-Shiny',
    'sm8b',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Reshiram GX URL maps this local expansion to Cardmarket GX-Ultra-Shiny and lower-case sm8b product code.',
    now()
  ),
  (
    'MEGA Start Deck 100 Battle Collection',
    'mC',
    'en',
    'MEGA-Start-Deck-100-Battle-Collection',
    'mC',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Arven''s Mabosstiff ex URL uses MEGA Start Deck 100 slug and mixed-case mC product code.',
    now()
  ),
  (
    'Magma Deck Kit',
    'advf',
    'en',
    'Magma-Deck-Kit',
    'advF',
    '',
    'set_code_padded_3',
    'pokemon',
    'verified',
    'Refinement log verified Magma Deck Kit uses mixed-case advF product codes and removes apostrophes from Team Magma names.',
    now()
  ),
  (
    'Mega Brave',
    'm1L',
    'en',
    'Mega-Brave',
    'm1L',
    '',
    'set_code_padded_3',
    'pokemon',
    'verified',
    'User verified Mega Venusaur ex URL uses Mega-Brave slug, V2 marker, and mixed-case m1L076 product code.',
    now()
  ),
  (
    'Paldean Fates',
    'paf',
    'en',
    'Paldean-Fates',
    'PAF',
    '',
    'set_code_padded_3',
    'pokemon',
    'verified',
    'Regression fix: Mew ex 232/091 previously resolved directly as Mew-ex-V2-PAF232; Paldean Fates must remain a curated direct-product expansion.',
    now()
  ),
  (
    'Scarlet & Violet Simplified Chinese Promos',
    'svp',
    'en',
    'Scarlet-Violet-Simplified-Chinese-Promos',
    'SV-PCS',
    '',
    'set_code_padded_3',
    'pokemon',
    'verified',
    'Refinement log verified Scarlet & Violet Simplified Chinese Promos drop the ampersand and use SV-PCS product codes.',
    now()
  ),
  (
    'White Flare - Poké Ball Reverse Holo',
    'zsv10w',
    'en',
    'White-Flare-Additionals',
    'xWHT',
    '',
    'set_code_padded_3',
    'pokemon',
    'verified',
    'Refinement log verified Poké Ball reverse rows live under White-Flare-Additionals and use xWHT product codes with V markers.',
    now()
  ),
  (
    'XY Black Star Promos',
    'xyp',
    'en',
    'XY-Black-Star-Promos',
    'XYPR',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'Refinement log verified XY Black Star Promos can use XYPRXY### product codes and occasional V markers.',
    now()
  ),
  (
    'Perfect Order',
    'm1S',
    'en',
    'Perfect-Order',
    'POR',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Perfect Order maps to POR product codes; Mega/full-art duplicates can require V1/V2 markers, while ordinary rows can use POR plus padded collector number.',
    now()
  ),
  (
    'World Championship Decks 2006',
    'wcd2006',
    'en',
    'WCD-2006',
    '',
    'WCD06',
    'context_code',
    'pokemon',
    'verified',
    'Refinement log verified WCD 2006 can use player/context code such as WCD06LM-016 plus a variant marker.',
    now()
  ),
  (
    'CSVH4pC: Reward Pack',
    'csvH4p',
    'en',
    'Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon',
    'CSVH4Cp',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified CSVH4pC Reward Pack products live under the Happy Set Cardmarket expansion and use mixed-case CSVH4Cp product codes.',
    now()
  )
on conflict (expansion_name, cardmarket_locale, cardmarket_expansion_slug, applies_to_card_type)
do update set
  cardtrader_expansion_code = excluded.cardtrader_expansion_code,
  cardmarket_set_code = excluded.cardmarket_set_code,
  cardmarket_context_code = excluded.cardmarket_context_code,
  number_format_rule = excluded.number_format_rule,
  confidence = excluded.confidence,
  notes = excluded.notes,
  verified_at = excluded.verified_at,
  updated_at = now();

insert into public.marketplace_cm_product_parsing (
  blueprint_id,
  cardmarket_locale,
  card_name,
  cardmarket_name,
  expansion_name,
  cardmarket_expansion_slug,
  collector_number,
  normalized_collector_number,
  cardmarket_set_code,
  cardmarket_context_code,
  cardmarket_variant_marker,
  cardmarket_product_slug,
  cardmarket_url,
  match_status,
  confidence,
  verification_method,
  verification_source,
  notes,
  verified_at
)
values
  (
    235975,
    'en',
    'Aroma Lady',
    'Aroma Lady',
    'Start Deck 100',
    'Start-Deck-100',
    '387/414',
    '387',
    'sI100',
    '',
    '',
    'Aroma-Lady-sI100387',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Start-Deck-100/Aroma-Lady-sI100387',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Start Deck 100 uses sI100 Cardmarket code.',
    now()
  ),
  (
    130677,
    'it',
    'Togekiss',
    'Togekiss',
    'Unbroken Bonds',
    'Unbroken-Bonds',
    'Holo Rare | 138/214',
    '138',
    'UNB',
    '',
    '',
    'Togekiss-UNB138',
    'https://www.cardmarket.com/it/Pokemon/Products/Singles/Unbroken-Bonds/Togekiss-UNB138',
    'verified',
    'verified',
    'user',
    'chat',
    'User provided as correct URL.',
    now()
  ),
  (
    141860,
    'en',
    'Training Center',
    'Training Center',
    'Rising Fist',
    'Rising-Fist',
    '92/096',
    '92',
    '',
    '',
    '',
    'Training-Center',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Rising-Fist/Training-Center',
    'verified',
    'verified',
    'user',
    'chat',
    'User provided as correct URL for Trainer/Stadium-style name-only slug.',
    now()
  ),
  (
    359203,
    'en',
    'Hop''s Zacian ex',
    'Hops Zacian ex',
    'MEGA Dream ex',
    'MEGA-Dream-ex',
    'Ultra Rare | 123/193',
    '123',
    'm2a',
    '',
    '',
    'Hops-Zacian-ex-m2a123',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/MEGA-Dream-ex/Hops-Zacian-ex-m2a123',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified apostrophe is removed, not split with hyphen.',
    now()
  ),
  (
    370349,
    'es',
    'Pokémon Fan Club',
    'Pokemon Fan Club',
    'CSM1c: Storming Emergence - Abundant',
    'Storming-Emergence-Abundant',
    'CSM1cC | 143/151',
    '143',
    'CSM1cC',
    '',
    'V1',
    'Pokemon-Fan-Club-V1-CSM1cC143',
    'https://www.cardmarket.com/es/Pokemon/Products/Singles/Storming-Emergence-Abundant/Pokemon-Fan-Club-V1-CSM1cC143',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Spanish locale, V1 marker, and Cardmarket expansion slug.',
    now()
  ),
  (
    370392,
    'en',
    'Cynthia',
    'Cynthia',
    'CSM1c: Storming Emergence - Abundant',
    'Storming-Emergence-Abundant',
    'CSM1cC | Ultra Rare | 186/151',
    '186/151',
    'CSM1cC',
    '',
    'V2',
    'Cynthia-V2-CSM1cC186',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Storming-Emergence-Abundant/Cynthia-V2-CSM1cC186',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected blueprint 370392: card_market_ids/idProduct alone is not the public URL; verified URL uses V2 marker.',
    now()
  ),
  (
    356893,
    'it',
    'Ambipom',
    'Ambipom',
    'Phantasmal Flames',
    'Phantasmal-Flames',
    'Illustration Rare | 107/094',
    '107',
    'PFL',
    '',
    'V2',
    'Ambipom-V2-PFL107',
    'https://www.cardmarket.com/it/Pokemon/Products/Singles/Phantasmal-Flames/Ambipom-V2-PFL107',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified V2 marker for the second Ambipom printing in Phantasmal Flames.',
    now()
  ),
  (
    132565,
    'en',
    'Tierno',
    'Tierno',
    'XY Trainer Kit: Pikachu Libre & Suicune (Suicune)',
    'XY-Trainer-Kit-Pikachu-Libre-Suicune',
    'Non-Holo | Trainer Kit 29/30',
    '29',
    'TK9S',
    '',
    '',
    'Tierno-TK9S-29',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/XY-Trainer-Kit-Pikachu-Libre-Suicune/Tierno-TK9S-29',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified English locale, shortened expansion slug, and TK9S code.',
    now()
  ),
  (
    124608,
    'en',
    'Dedenne',
    'Dedenne',
    'Phantom Forces',
    'Phantom-Forces',
    '70/119',
    '70',
    'PHF',
    '',
    '',
    'Dedenne-PHF70',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Phantom-Forces/Dedenne-PHF70',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified English locale and code-suffixed product slug.',
    now()
  ),
  (
    320561,
    'en',
    'Buzzwole GX',
    'Buzzwole GX',
    'World Championship Decks 2018',
    'WCD-2018',
    'WCD 2018 | Naohito Inoue | 057/111',
    '057',
    '',
    'WCD18CIN',
    '',
    'Buzzwole-GX-WCD18CIN-057',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/WCD-2018/Buzzwole-GX-WCD18CIN-057',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified WCD URL uses player/context code, not CardTrader wcd2018 code.',
    now()
  ),
  (
    384357,
    'en',
    'Koraidon ex',
    'Koraidon ex',
    'CSVH4pC: Reward Pack',
    'Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon',
    '005/053',
    '005',
    'CSVH4Cp',
    '',
    '',
    'Koraidon-ex-CSVH4Cp005',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon/Koraidon-ex-CSVH4Cp005',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Reward Pack Koraidon ex maps to the Happy Set Cardmarket expansion slug and mixed-case CSVH4Cp product code.',
    now()
  ),
  (
    384358,
    'en',
    'Snorlax ex',
    'Snorlax ex',
    'CSVH4pC: Reward Pack',
    'Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon',
    '006/053',
    '006',
    'CSVH4Cp',
    '',
    '',
    'Snorlax-ex-CSVH4Cp006',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon/Snorlax-ex-CSVH4Cp006',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Reward Pack Snorlax ex maps to the Happy Set Cardmarket expansion slug and mixed-case CSVH4Cp product code.',
    now()
  ),
  (
    315033,
    'en',
    'Double Rainbow Energy',
    'Double Rainbow Energy',
    'World Championship Decks 2007',
    'WCD-2007',
    'WCD 2007 | Christopher Gilhousen | 088/108',
    '088',
    '',
    'WCD07CG',
    '',
    'Double-Rainbow-Energy-WCD07CG-088',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/WCD-2007/Double-Rainbow-Energy-WCD07CG-088',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: WCD 2007 requires WCD07CG context code.',
    now()
  ),
  (
    123536,
    'en',
    'Kabutops',
    'Kabutops',
    'Neo Discovery',
    'Neo-Discovery',
    '25/75',
    '25',
    'NDI',
    '',
    '',
    'Kabutops-NDI25',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Neo-Discovery/Kabutops-NDI25',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: Neo Discovery uses NDI25 and no inferred V marker.',
    now()
  ),
  (
    388130,
    'en',
    'Friends in Alola',
    'Friends in Alola',
    'S-P: Sword & Shield Promos',
    'Sword-Shield-Simplified-Chinese-Promos',
    '081/S-P',
    '081',
    'PCS',
    '',
    '',
    'Friends-in-Alola-S-PCS081',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Sword-Shield-Simplified-Chinese-Promos/Friends-in-Alola-S-PCS081',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: this card lives under Simplified Chinese Promos and uses S-PCS081.',
    now()
  ),
  (
    236544,
    'en',
    'Rapidash',
    'Rapidash',
    'SWSH Black Star Promos',
    'SWSH-Black-Star-Promos',
    '270',
    '270',
    'SWSH',
    '',
    '',
    'Rapidash-SWSH270',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/SWSH-Black-Star-Promos/Rapidash-SWSH270',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: SWSH Black Star Promos use SWSH product code.',
    now()
  ),
  (
    136333,
    'en',
    'Lickitung',
    'Lickitung',
    'Clash at the Summit',
    'Clash-at-the-Summit',
    '061/080',
    '061',
    'L3',
    '',
    '',
    'Lickitung-L3061',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Clash-at-the-Summit/Lickitung-L3061',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: Clash at the Summit uses L3 plus unpadded collector number.',
    now()
  ),
  (
    369312,
    'en',
    'Lum Berry',
    'Lum Berry',
    'CS1b: Dynamax Clash - Flame',
    'Dynamax-Clash-Flame',
    '130/157',
    '130',
    'CS1bC',
    '',
    '',
    'Lum-Berry-CS1bC130',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Dynamax-Clash-Flame/Lum-Berry-CS1bC130',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: CS1b Flame uses Dynamax-Clash-Flame slug and CS1bC product code.',
    now()
  ),
  (
    228478,
    'en',
    'Detective Pikachu',
    'Detective Pikachu',
    'SM Black Star Promos',
    'SM-Black-Star-Promos',
    'SM194',
    '194',
    'OSSM',
    '',
    'V2',
    'Detective-Pikachu-V2-OSSM194',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/SM-Black-Star-Promos/Detective-Pikachu-V2-OSSM194',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected sampled URL: Detective Pikachu uses OSSM194 and Cardmarket V2 marker.',
    now()
  ),
  (
    142010,
    'en',
    'Dark Steelix',
    'Dark Steelix',
    'Rocket Gang Strikes Back',
    'Rocket-Gang-Strikes-Back',
    'Holo Rare | 072/084',
    '072',
    'PCG3',
    '',
    '',
    'Dark-Steelix-PCG3072',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Rocket-Gang-Strikes-Back/Dark-Steelix-PCG3072',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected blueprint 142010: Cardmarket uses PCG3 plus three-digit collector number; query filters are intentionally not persisted in canonical URL.',
    now()
  ),
  (
    113087,
    'en',
    'Throh',
    'Throh',
    'Cosmic Eclipse',
    'Cosmic-Eclipse',
    '118/236',
    '118',
    'CEC',
    '',
    '',
    'Throh-CEC118',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Cosmic-Eclipse/Throh-CEC118',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected comparison sample: both name-only parser and TCGdex sm12-derived URL were wrong; Cardmarket uses CEC118.',
    now()
  ),
  (
    383285,
    'en',
    'Energy Retrieval',
    'Energy Retrieval',
    'CSM1d: Storming Emergence GX Starter Deck',
    'Storming-Emergence-GX-Starter-Deck',
    'CSM1dC | 230/324',
    '230',
    'CSM1DC',
    '',
    '',
    'Energy-Retrieval-CSM1DC230',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Storming-Emergence-GX-Starter-Deck/Energy-Retrieval-CSM1DC230',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected comparison sample: CSM1d uses Storming-Emergence-GX-Starter-Deck slug and CSM1DC230 product code.',
    now()
  ),
  (
    110803,
    'en',
    'Ralts',
    'Ralts',
    'BREAKthrough',
    'BREAKthrough',
    '100/162',
    '100',
    'BKT',
    '',
    '',
    'Ralts-BKT100',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/BREAKthrough/Ralts-BKT100',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected comparison sample: inferred V2 marker was wrong for this Ralts; Cardmarket uses Ralts-BKT100.',
    now()
  ),
  (
    137077,
    'en',
    'Pikachu',
    'Pikachu',
    'Darkness that Consumes Light',
    'Darkness-that-Consumes-Light',
    '013/051',
    '013',
    '',
    '',
    '',
    'Pikachu',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Darkness-that-Consumes-Light/Pikachu',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified while navigating: query filters language=1 and minCondition=2 are listing filters and are not persisted in canonical product URL.',
    now()
  ),
  (
    138766,
    'en',
    'Reshiram GX',
    'Reshiram GX',
    'High Class Pack GX Ultra Shiny',
    'GX-Ultra-Shiny',
    'Shiny Rare | 211/150',
    '211',
    'sm8b',
    '',
    'V2',
    'Reshiram-GX-V2-sm8b211',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/GX-Ultra-Shiny/Reshiram-GX-V2-sm8b211',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected blueprint 138766: Cardmarket uses GX-Ultra-Shiny slug, V2 marker, and lower-case sm8b211 product code.',
    now()
  ),
  (
    364150,
    'en',
    'Arven''s Mabosstiff ex',
    'Arvens Mabosstiff ex',
    'MEGA Start Deck 100 Battle Collection',
    'MEGA-Start-Deck-100-Battle-Collection',
    'Ultra Rare | 484/742',
    '484',
    'mC',
    '',
    '',
    'Arvens-Mabosstiff-ex-mC484',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/MEGA-Start-Deck-100-Battle-Collection/Arvens-Mabosstiff-ex-mC484',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected blueprint 364150: Cardmarket removes the apostrophe in Arven''s and uses mixed-case mC484 product code.',
    now()
  ),
  (
    344716,
    'en',
    'Mega Venusaur ex',
    'Mega Venusaur ex',
    'Mega Brave',
    'Mega-Brave',
    'Full-Art | 076/063',
    '076',
    'm1L',
    '',
    'V2',
    'Mega-Venusaur-ex-V2-m1L076',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Mega-Brave/Mega-Venusaur-ex-V2-m1L076',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected blueprint 344716: Cardmarket uses V2 and mixed-case m1L076 product code for Mega Brave.',
    now()
  ),
  (
    378949,
    'en',
    'Mega Zygarde ex',
    'Mega Zygarde ex',
    'Perfect Order',
    'Perfect-Order',
    'Full-Art | 104/088',
    '104',
    'POR',
    '',
    'V2',
    'Mega-Zygarde-ex-V2-POR104',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Perfect-Order/Mega-Zygarde-ex-V2-POR104',
    'verified',
    'verified',
    'user',
    'chat',
    'User corrected blueprint 378949: Cardmarket uses Perfect-Order slug, V2 marker, and POR104 product code.',
    now()
  ),
  (
    212782,
    'en',
    'Sweet Honey',
    'Sweet Honey',
    'Astral Radiance',
    'Astral-Radiance',
    '153/189',
    '153',
    'ASR',
    '',
    '',
    'Sweet-Honey-ASR153',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Astral-Radiance/Sweet-Honey-ASR153',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 1: Astral Radiance Trainer item uses ASR153 code-suffixed product slug, not name-only.',
    now()
  ),
  (
    378857,
    'en',
    'Decidueye ex',
    'Decidueye ex',
    'Perfect Order',
    'Perfect-Order',
    'Ultra Rare | 012/088',
    '012',
    'POR',
    '',
    'V1',
    'Decidueye-ex-V1-POR012',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Perfect-Order/Decidueye-ex-V1-POR012',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 2: Perfect Order duplicate/ultra rare Decidueye ex needs V1 marker and POR012.',
    now()
  ),
  (
    314822,
    'en',
    'Girafarig',
    'Girafarig',
    'World Championship Decks 2006',
    'WCD-2006',
    'WCD 2006 | Jason Klaczynski | 016/092',
    '016',
    '',
    'WCD06LM',
    'V1',
    'Girafarig-V1-WCD06LM-016',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/WCD-2006/Girafarig-V1-WCD06LM-016',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 3: WCD 2006 Jason Klaczynski deck uses WCD06LM context code, V1 marker, and hyphenated collector number.',
    now()
  ),
  (
    274416,
    'en',
    'Mew ex',
    'Mew ex',
    'Paldean Fates',
    'Paldean-Fates',
    'Special Illustration Rare | 232/091',
    '232',
    'PAF',
    '',
    'V2',
    'Mew-ex-V2-PAF232',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Paldean-Fates/Mew-ex-V2-PAF232',
    'verified',
    'verified',
    'user',
    'regression',
    'Regression fix: this Paldean Fates Mew ex direct URL includes V2 and must be preserved exactly, not rebuilt without the variant marker.',
    now()
  ),
  (
    114322,
    'en',
    'Hydreigon',
    'Hydreigon',
    'Dragon Majesty',
    'Dragon-Majesty',
    'Holo Rare | 33/70',
    '33',
    'DRM',
    '',
    '',
    'Hydreigon-DRM33',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Dragon-Majesty/Hydreigon-DRM33',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 10: Dragon Majesty Hydreigon uses DRM33 code-suffixed product slug.',
    now()
  ),
  (
    132124,
    'en',
    'Jirachi',
    'Jirachi',
    'XY Black Star Promos',
    'XY-Black-Star-Promos',
    'Holo Promo | XY67a',
    'XY67a',
    'XYPR',
    '',
    'V2',
    'Jirachi-V2-XYPRXY67a',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/XY-Black-Star-Promos/Jirachi-V2-XYPRXY67a',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 9: XY Black Star promo Jirachi keeps XY collector text inside XYPRXY67a and requires V2 marker.',
    now()
  ),
  (
    343260,
    'en',
    'Durant',
    'Durant',
    'White Flare - Poké Ball Reverse Holo',
    'White-Flare-Additionals',
    'Poké Ball Reverse Holo | 070/086',
    '070',
    'xWHT',
    '',
    'V2',
    'Durant-V2-xWHT070',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/White-Flare-Additionals/Durant-V2-xWHT070',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 8: White Flare Poké Ball reverse maps to White-Flare-Additionals with V2 and xWHT070.',
    now()
  ),
  (
    315302,
    'en',
    'Team Magma''s Rhyhorn',
    'Team Magmas Rhyhorn',
    'Magma Deck Kit',
    'Magma-Deck-Kit',
    '007/033',
    '007',
    'advF',
    '',
    '',
    'Team-Magmas-Rhyhorn-advF007',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Magma-Deck-Kit/Team-Magmas-Rhyhorn-advF007',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 7: Magma Deck Kit removes apostrophe and uses mixed-case advF007 product code.',
    now()
  ),
  (
    331658,
    'en',
    'Toedscool',
    'Toedscool',
    'Scarlet & Violet Simplified Chinese Promos',
    'Scarlet-Violet-Simplified-Chinese-Promos',
    'Mission Reward Promo | 005/SV-P',
    '005',
    'SV-PCS',
    '',
    '',
    'Toedscool-SV-PCS005',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Scarlet-Violet-Simplified-Chinese-Promos/Toedscool-SV-PCS005',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 6: Scarlet & Violet Simplified Chinese promo uses Scarlet-Violet slug and SV-PCS005 product code.',
    now()
  ),
  (
    132211,
    'en',
    'Rayquaza',
    'Rayquaza',
    'XY Black Star Promos',
    'XY-Black-Star-Promos',
    'Holo Promo | XY141',
    'XY141',
    'XYPR',
    '',
    '',
    'Rayquaza-XYPRXY141',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/XY-Black-Star-Promos/Rayquaza-XYPRXY141',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 5: XY Black Star promo Rayquaza uses XYPRXY141 without V marker.',
    now()
  ),
  (
    135242,
    'en',
    'Rescue',
    'Pokemon Rescue',
    'Advent of Arceus',
    'Advent-of-Arceus',
    '080/090',
    '080',
    'Pt4',
    '',
    '',
    'Pokemon-Rescue-Pt4080',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Advent-of-Arceus/Pokemon-Rescue-Pt4080',
    'verified',
    'verified',
    'user',
    'debug-refinement-log',
    'Refinement log row 4: local Rescue is Cardmarket Pokemon Rescue and uses mixed-case Pt4080.',
    now()
  ),
  (
    116587,
    'en',
    'Mew ex',
    'Mew ex',
    'EX Holon Phantoms',
    'EX-Holon-Phantoms',
    'Holo Rare | 100/110',
    '100',
    'HP',
    '',
    '',
    'Mew-ex-HP100',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/EX-Holon-Phantoms/Mew-ex-HP100',
    'verified',
    'verified',
    'user',
    'chat',
    'User supplied exact Cardmarket URL for Mew ex HP100; EX Holon Phantoms uses HP product codes.',
    now()
  )
on conflict (blueprint_id, cardmarket_locale)
do update set
  card_name = excluded.card_name,
  cardmarket_name = excluded.cardmarket_name,
  expansion_name = excluded.expansion_name,
  cardmarket_expansion_slug = excluded.cardmarket_expansion_slug,
  collector_number = excluded.collector_number,
  normalized_collector_number = excluded.normalized_collector_number,
  cardmarket_set_code = excluded.cardmarket_set_code,
  cardmarket_context_code = excluded.cardmarket_context_code,
  cardmarket_variant_marker = excluded.cardmarket_variant_marker,
  cardmarket_product_slug = excluded.cardmarket_product_slug,
  cardmarket_url = excluded.cardmarket_url,
  match_status = excluded.match_status,
  confidence = excluded.confidence,
  verification_method = excluded.verification_method,
  verification_source = excluded.verification_source,
  notes = excluded.notes,
  verified_at = excluded.verified_at,
  updated_at = now();

insert into public.marketplace_cm_expansion_rules (
  expansion_name,
  cardmarket_locale,
  cardtrader_expansion_code,
  cardmarket_expansion_slug,
  cardmarket_set_code,
  cardmarket_context_code,
  number_format_rule,
  applies_to_card_type,
  confidence,
  source,
  notes,
  verified_at
)
select distinct on (expansion_name, cardmarket_locale, applies_to_card_type)
  expansion_name,
  cardmarket_locale,
  cardtrader_expansion_code,
  cardmarket_expansion_slug,
  cardmarket_set_code,
  cardmarket_context_code,
  number_format_rule,
  applies_to_card_type,
  confidence,
  'cardmarket-parsing-seeds',
  notes,
  verified_at
from public.marketplace_cm_expansion_parsing
where confidence in ('verified', 'manual')
order by expansion_name, cardmarket_locale, applies_to_card_type, verified_at desc nulls last, updated_at desc
on conflict (expansion_name, cardmarket_locale, applies_to_card_type)
do update set
  cardtrader_expansion_code = excluded.cardtrader_expansion_code,
  cardmarket_expansion_slug = excluded.cardmarket_expansion_slug,
  cardmarket_set_code = excluded.cardmarket_set_code,
  cardmarket_context_code = excluded.cardmarket_context_code,
  number_format_rule = excluded.number_format_rule,
  confidence = excluded.confidence,
  source = excluded.source,
  notes = excluded.notes,
  verified_at = excluded.verified_at,
  updated_at = now();

insert into public.marketplace_cm_verified_links (
  blueprint_id,
  cardmarket_locale,
  cardmarket_url,
  cardmarket_product_slug,
  card_name,
  expansion_name,
  collector_number,
  source,
  confidence,
  notes,
  verified_at
)
select
  blueprint_id,
  cardmarket_locale,
  cardmarket_url,
  cardmarket_product_slug,
  card_name,
  expansion_name,
  collector_number,
  verification_source,
  case when match_status = 'manual' then 'manual' else 'verified' end,
  notes,
  coalesce(verified_at, now())
from public.marketplace_cm_product_parsing
where match_status in ('verified', 'manual')
on conflict (blueprint_id, cardmarket_locale)
do update set
  cardmarket_url = excluded.cardmarket_url,
  cardmarket_product_slug = excluded.cardmarket_product_slug,
  card_name = excluded.card_name,
  expansion_name = excluded.expansion_name,
  collector_number = excluded.collector_number,
  source = excluded.source,
  confidence = excluded.confidence,
  notes = excluded.notes,
  verified_at = excluded.verified_at,
  updated_at = now();
