insert into public.marketplace_cm_expansion_parsing (
  expansion_name,
  cardtrader_expansion_code,
  cardmarket_locale,
  cardmarket_expansion_slug,
  cardmarket_set_code,
  cardmarket_context_code,
  number_format_rule,
  applies_to_card_type,
  confidence,
  notes,
  verified_at
)
values
  (
    'Start Deck 100',
    'sl',
    'en',
    'Start-Deck-100',
    'sI100',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Aroma Lady URL uses Cardmarket set code sI100, not CardTrader sl/SL.',
    now()
  ),
  (
    'Unbroken Bonds',
    'unb',
    'it',
    'Unbroken-Bonds',
    'UNB',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Togekiss URL uses code-suffixed product slug.',
    now()
  ),
  (
    'Night Unison',
    'sm9a',
    'it',
    'Night-Unison',
    '',
    '',
    'name_only',
    'trainer',
    'verified',
    'User verified Trainer card Surprise Box URL uses name-only product slug.',
    now()
  ),
  (
    'Rising Fist',
    'xy2',
    'en',
    'Rising-Fist',
    '',
    '',
    'name_only',
    'trainer',
    'verified',
    'User verified Trainer/Stadium card Training Center URL uses name-only product slug.',
    now()
  ),
  (
    'MEGA Dream ex',
    'm2a',
    'en',
    'MEGA-Dream-ex',
    'm2a',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Hops Zacian ex URL uses lower-case m2a product code and no apostrophe separator.',
    now()
  ),
  (
    'CSM1c: Storming Emergence - Abundant',
    'csm1c',
    'es',
    'Storming-Emergence-Abundant',
    'CSM1cC',
    '',
    'set_code_unpadded',
    'trainer',
    'verified',
    'User verified Pokemon Fan Club URL drops CSM prefix from expansion slug and includes V1 marker.',
    now()
  ),
  (
    'Skyridge',
    'skg',
    'en',
    'Skyridge',
    'SK',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'Cardmarket Skyridge URLs use SK, not CardTrader skg/SKG; verified from Lapras and Steelix examples.',
    now()
  ),
  (
    'Phantasmal Flames',
    'pfl',
    'it',
    'Phantasmal-Flames',
    'PFL',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Ambipom Illustration Rare URL uses Italian locale and V2 marker because Ambipom has multiple printings in this expansion.',
    now()
  ),
  (
    'Phantom Forces',
    'phf',
    'en',
    'Phantom-Forces',
    'PHF',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified Dedenne URL uses English locale and code-suffixed product slug.',
    now()
  ),
  (
    'XY Trainer Kit: Pikachu Libre & Suicune (Suicune)',
    'suicune',
    'en',
    'XY-Trainer-Kit-Pikachu-Libre-Suicune',
    'TK9S',
    '',
    'context_code',
    'trainer',
    'verified',
    'User verified Tierno URL uses English locale, shortened expansion slug, and TK9S context code.',
    now()
  ),
  (
    'World Championship Decks 2018',
    'wcd2018',
    'en',
    'WCD-2018',
    '',
    'WCD18CIN',
    'context_code',
    'pokemon',
    'verified',
    'User verified Buzzwole GX URL uses WCD context/player code.',
    now()
  ),
  (
    'CSVH4pC: Reward Pack',
    'csvH4p',
    'en',
    'Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon',
    'CSVH4Cp',
    '',
    'set_code_unpadded',
    'pokemon',
    'verified',
    'User verified CSVH4pC Reward Pack products live under the Happy Set Cardmarket expansion and use mixed-case CSVH4Cp product codes.',
    now()
  )
on conflict (expansion_name, cardmarket_locale, cardmarket_expansion_slug, applies_to_card_type)
do update set
  cardtrader_expansion_code = excluded.cardtrader_expansion_code,
  cardmarket_set_code = excluded.cardmarket_set_code,
  cardmarket_context_code = excluded.cardmarket_context_code,
  number_format_rule = excluded.number_format_rule,
  confidence = excluded.confidence,
  notes = excluded.notes,
  verified_at = excluded.verified_at,
  updated_at = now();

insert into public.marketplace_cm_product_parsing (
  blueprint_id,
  cardmarket_locale,
  card_name,
  cardmarket_name,
  expansion_name,
  cardmarket_expansion_slug,
  collector_number,
  normalized_collector_number,
  cardmarket_set_code,
  cardmarket_context_code,
  cardmarket_variant_marker,
  cardmarket_product_slug,
  cardmarket_url,
  match_status,
  confidence,
  verification_method,
  verification_source,
  notes,
  verified_at
)
values
  (
    235975,
    'en',
    'Aroma Lady',
    'Aroma Lady',
    'Start Deck 100',
    'Start-Deck-100',
    '387/414',
    '387',
    'sI100',
    '',
    '',
    'Aroma-Lady-sI100387',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Start-Deck-100/Aroma-Lady-sI100387',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Start Deck 100 uses sI100 Cardmarket code.',
    now()
  ),
  (
    130677,
    'it',
    'Togekiss',
    'Togekiss',
    'Unbroken Bonds',
    'Unbroken-Bonds',
    'Holo Rare | 138/214',
    '138',
    'UNB',
    '',
    '',
    'Togekiss-UNB138',
    'https://www.cardmarket.com/it/Pokemon/Products/Singles/Unbroken-Bonds/Togekiss-UNB138',
    'verified',
    'verified',
    'user',
    'chat',
    'User provided as correct URL.',
    now()
  ),
  (
    141860,
    'en',
    'Training Center',
    'Training Center',
    'Rising Fist',
    'Rising-Fist',
    '92/096',
    '92',
    '',
    '',
    '',
    'Training-Center',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Rising-Fist/Training-Center',
    'verified',
    'verified',
    'user',
    'chat',
    'User provided as correct URL for Trainer/Stadium-style name-only slug.',
    now()
  ),
  (
    359203,
    'en',
    'Hop''s Zacian ex',
    'Hops Zacian ex',
    'MEGA Dream ex',
    'MEGA-Dream-ex',
    'Ultra Rare | 123/193',
    '123',
    'm2a',
    '',
    '',
    'Hops-Zacian-ex-m2a123',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/MEGA-Dream-ex/Hops-Zacian-ex-m2a123',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified apostrophe is removed, not split with hyphen.',
    now()
  ),
  (
    370349,
    'es',
    'Pokémon Fan Club',
    'Pokemon Fan Club',
    'CSM1c: Storming Emergence - Abundant',
    'Storming-Emergence-Abundant',
    'CSM1cC | 143/151',
    '143',
    'CSM1cC',
    '',
    'V1',
    'Pokemon-Fan-Club-V1-CSM1cC143',
    'https://www.cardmarket.com/es/Pokemon/Products/Singles/Storming-Emergence-Abundant/Pokemon-Fan-Club-V1-CSM1cC143',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Spanish locale, V1 marker, and Cardmarket expansion slug.',
    now()
  ),
  (
    356893,
    'it',
    'Ambipom',
    'Ambipom',
    'Phantasmal Flames',
    'Phantasmal-Flames',
    'Illustration Rare | 107/094',
    '107',
    'PFL',
    '',
    'V2',
    'Ambipom-V2-PFL107',
    'https://www.cardmarket.com/it/Pokemon/Products/Singles/Phantasmal-Flames/Ambipom-V2-PFL107',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified V2 marker for the second Ambipom printing in Phantasmal Flames.',
    now()
  ),
  (
    132565,
    'en',
    'Tierno',
    'Tierno',
    'XY Trainer Kit: Pikachu Libre & Suicune (Suicune)',
    'XY-Trainer-Kit-Pikachu-Libre-Suicune',
    'Non-Holo | Trainer Kit 29/30',
    '29',
    'TK9S',
    '',
    '',
    'Tierno-TK9S-29',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/XY-Trainer-Kit-Pikachu-Libre-Suicune/Tierno-TK9S-29',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified English locale, shortened expansion slug, and TK9S code.',
    now()
  ),
  (
    124608,
    'en',
    'Dedenne',
    'Dedenne',
    'Phantom Forces',
    'Phantom-Forces',
    '70/119',
    '70',
    'PHF',
    '',
    '',
    'Dedenne-PHF70',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Phantom-Forces/Dedenne-PHF70',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified English locale and code-suffixed product slug.',
    now()
  ),
  (
    320561,
    'en',
    'Buzzwole GX',
    'Buzzwole GX',
    'World Championship Decks 2018',
    'WCD-2018',
    'WCD 2018 | Naohito Inoue | 057/111',
    '057',
    '',
    'WCD18CIN',
    '',
    'Buzzwole-GX-WCD18CIN-057',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/WCD-2018/Buzzwole-GX-WCD18CIN-057',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified WCD URL uses player/context code, not CardTrader wcd2018 code.',
    now()
  ),
  (
    384357,
    'en',
    'Koraidon ex',
    'Koraidon ex',
    'CSVH4pC: Reward Pack',
    'Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon',
    '005/053',
    '005',
    'CSVH4Cp',
    '',
    '',
    'Koraidon-ex-CSVH4Cp005',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon/Koraidon-ex-CSVH4Cp005',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Reward Pack Koraidon ex maps to the Happy Set Cardmarket expansion slug and mixed-case CSVH4Cp product code.',
    now()
  ),
  (
    384358,
    'en',
    'Snorlax ex',
    'Snorlax ex',
    'CSVH4pC: Reward Pack',
    'Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon',
    '006/053',
    '006',
    'CSVH4Cp',
    '',
    '',
    'Snorlax-ex-CSVH4Cp006',
    'https://www.cardmarket.com/en/Pokemon/Products/Singles/Happy-Set-Decidueye-Melmetal-Koraidon-Miraidon/Snorlax-ex-CSVH4Cp006',
    'verified',
    'verified',
    'user',
    'chat',
    'User verified Reward Pack Snorlax ex maps to the Happy Set Cardmarket expansion slug and mixed-case CSVH4Cp product code.',
    now()
  )
on conflict (blueprint_id, cardmarket_locale)
do update set
  card_name = excluded.card_name,
  cardmarket_name = excluded.cardmarket_name,
  expansion_name = excluded.expansion_name,
  cardmarket_expansion_slug = excluded.cardmarket_expansion_slug,
  collector_number = excluded.collector_number,
  normalized_collector_number = excluded.normalized_collector_number,
  cardmarket_set_code = excluded.cardmarket_set_code,
  cardmarket_context_code = excluded.cardmarket_context_code,
  cardmarket_variant_marker = excluded.cardmarket_variant_marker,
  cardmarket_product_slug = excluded.cardmarket_product_slug,
  cardmarket_url = excluded.cardmarket_url,
  match_status = excluded.match_status,
  confidence = excluded.confidence,
  verification_method = excluded.verification_method,
  verification_source = excluded.verification_source,
  notes = excluded.notes,
  verified_at = excluded.verified_at,
  updated_at = now();
